-- ANALYSIS QUESTIONS
SELECT * FROM zomatodata;

-- MOVING COUNT OF RESTAURANTS IN INDIAN CITIES
SELECT COUNTRY_NAME,City,Locality,COUNT(Locality) TOTAL_REST,
SUM(COUNT(Locality)) OVER(PARTITION BY City ORDER BY Locality DESC)
FROM zomatodata
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY  COUNTRY_NAME,City,Locality;

-- SEARCHING FOR PERCENTAGE OF RESTAURANTS IN ALL THE COUNTRIES

CREATE OR REPLACE VIEW TOTAL_COUNT AS
SELECT 
    COUNTRY_NAME,
    COUNT(RestaurantID) OVER() AS TOTAL_REST
FROM zomatodata;

-- if intention is to show each country only once with the total number of restaurants in the entire table

CREATE OR REPLACE VIEW TOTAL_COUNT AS
SELECT DISTINCT
    COUNTRY_NAME,
    COUNT(RestaurantID) OVER() AS TOTAL_REST
FROM zomatodata;
SELECT * FROM TOTAL_COUNT;





-- SEARCHING FOR PERCENTAGE OF RESTAURANTS IN ALL THE COUNTRIES
CREATE OR REPLACE VIEW TOTAL_COUNT AS
SELECT 
    COUNTRY_NAME,
    COUNT(RestaurantID) OVER() AS TOTAL_REST
FROM zomatodata;
SELECT * FROM TOTAL_COUNT;

WITH CT1 AS
(
    SELECT 
        COUNTRY_NAME,
        COUNT(RestaurantID) AS REST_COUNT
    FROM zomatodata
    GROUP BY COUNTRY_NAME
)
SELECT *
FROM CT1;

CREATE OR REPLACE VIEW TOTAL_COUNT AS
SELECT COUNT(RestaurantID) AS TOTAL_REST
FROM zomatodata;

WITH CT1 AS
(SELECT COUNTRY_NAME, COUNT(RestaurantID) AS REST_COUNT 
   FROM zomatodata GROUP BY COUNTRY_NAME)
SELECT A.COUNTRY_NAME, A.REST_COUNT,
    ROUND((A.REST_COUNT / B.TOTAL_REST) * 100,2) AS REST_PERCENTAGE
FROM CT1 A CROSS JOIN TOTAL_COUNT B
ORDER BY REST_PERCENTAGE DESC;



-- WHICH COUNTRIES AND HOW MANY RESTAURANTS WITH PERCENTAGE PROVIDES ONLINE DELIVERY OPTION

CREATE OR REPLACE VIEW COUNTRY_REST AS
SELECT COUNTRY_NAME, COUNT(RestaurantID) AS REST_COUNT
FROM zomatodata GROUP BY COUNTRY_NAME;

SELECT * FROM COUNTRY_REST
ORDER BY REST_COUNT DESC;

SELECT A.COUNTRY_NAME, COUNT(A.RestaurantID) AS TOTAL_REST,
    ROUND( COUNT(A.RestaurantID) / B.REST_COUNT * 100,2) AS ONLINE_DELIVERY_PERCENTAGE
FROM zomatodata A JOIN COUNTRY_REST B ON A.COUNTRY_NAME = B.COUNTRY_NAME
WHERE A.Has_Online_delivery = 'YES'
GROUP BY A.COUNTRY_NAME, B.REST_COUNT ORDER BY TOTAL_REST DESC;

-- FINDING FROM WHICH CITY AND LOCALITY IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO
WITH CT1 AS(
SELECT City,Locality,COUNT(RestaurantID) REST_COUNT
FROM zomatodata WHERE COUNTRY_NAME = 'INDIA'
GROUP BY CITY,LOCALITY ORDER BY 3 DESC
)
SELECT Locality,REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1);



-- TYPES OF FOODS ARE AVAILABLE IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO
WITH CT1 AS 
(SELECT City,Locality,COUNT(RestaurantID) REST_COUNT
FROM zomatodata
WHERE COUNTRY_NAME = 'INDIA'
GROUP BY CITY,LOCALITY
ORDER BY 3 DESC
),
CT2 AS (SELECT Locality,REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1)),
CT3 AS (SELECT Locality,Cuisines FROM zomatodata)
SELECT  A.Locality, B.Cuisines
FROM  CT2 A JOIN CT3 B
ON A.Locality = B.Locality;


-- MOST POPULAR FOOD IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO

WITH CT1 AS(SELECT City, Locality, COUNT(RestaurantID) AS REST_COUNT
    FROM zomatodata WHERE COUNTRY_NAME = 'INDIA' GROUP BY City, Locality),
CT2 AS(SELECT Locality, REST_COUNT FROM CT1
    WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1))
SELECT A.Cuisines, COUNT(*) AS CUISINE_COUNT
FROM zomatodata A JOIN CT2 B ON A.Locality = B.Locality
WHERE A.Cuisines IS NOT NULL GROUP BY A.Cuisines
ORDER BY CUISINE_COUNT DESC;

-- WHICH LOCALITIES IN INDIA HAS THE LOWEST RESTAURANTS LISTED IN ZOMATO
WITH CT1 AS (SELECT City,Locality, COUNT(RestaurantID) REST_COUNT
FROM zomatodata WHERE COUNTRY_NAME = 'INDIA'
GROUP BY City,Locality
 ORDER BY 3 DESC
)
SELECT * FROM CT1 WHERE REST_COUNT = (SELECT MIN(REST_COUNT) FROM CT1) ORDER BY CITY;

-- HOW MANY RESTAURANTS OFFER TABLE BOOKING OPTION IN INDIA WHERE THE MAX RESTAURANTS ARE LISTED IN ZOMATO
WITH CT1 AS (SELECT City,Locality,COUNT(RestaurantID) REST_COUNT
FROM zomatodata WHERE COUNTRY_NAME = 'INDIA' GROUP BY CITY,LOCALITY
-- ORDER BY 3 DESC 
),
CT2 AS ( SELECT Locality,REST_COUNT FROM CT1 WHERE REST_COUNT = (SELECT MAX(REST_COUNT) FROM CT1)),
CT3 AS ( SELECT Locality,Has_Table_booking TABLE_BOOKING FROM zomatodata)
SELECT A.Locality, COUNT(A.TABLE_BOOKING) TABLE_BOOKING_OPTION
FROM CT3 A JOIN CT2 B ON A.Locality = B.Locality WHERE A.TABLE_BOOKING = 'YES'
GROUP BY A.Locality;


-- HOW RATING AFFECTS IN MAX LISTED RESTAURANTS WITH AND WITHOUT TABLE BOOKING OPTION (Connaught Place)

SELECT 'WITH_TABLE' TABLE_BOOKING_OPT,COUNT(Has_Table_booking) TOTAL_REST, ROUND(AVG(Rating),2) AVG_RATING
FROM zomatodata WHERE Has_Table_booking = 'YES' AND Locality = 'Connaught Place'
UNION SELECT 'WITHOUT_TABLE' TABLE_BOOKING_OPT,COUNT(Has_Table_booking) TOTAL_REST, ROUND(AVG(Rating),2) AVG_RATING
FROM zomatodata WHERE Has_Table_booking = 'NO' AND Locality = 'Connaught Place';


-- AVG RATING OF RESTS LOCATION WISE

SELECT COUNTRY_NAME,City,Locality, 
COUNT(RestaurantID) TOTAL_REST ,ROUND(AVG(CAST(Rating AS DECIMAL)),2) AVG_RATING
FROM zomatodata
GROUP BY COUNTRY_NAME,City,Locality
ORDER BY 4 DESC;


-- FINDING THE BEST RESTAURANTS WITH MODRATE COST FOR TWO IN INDIA HAVING INDIAN CUISINES
SELECT * FROM zomatodata WHERE COUNTRY_NAME = 'INDIA'
AND Has_Table_booking = 'YES'
AND Has_Online_delivery = 'YES'
AND Price_range <= 3
AND Votes > 1000
AND Average_Cost_for_two < 1000
AND Rating > 4
AND Cuisines LIKE '%INDIA%';



-- FIND ALL THE RESTAURANTS THOSE WHO ARE OFFERING TABLE BOOKING OPTIONS WITH PRICE RANGE AND HAS HIGH RATING
SELECT Price_range, COUNT(Has_Table_booking) NO_OF_REST
FROM zomatodata
WHERE Rating >= 4.5
AND Has_Table_booking = 'YES'
GROUP BY Price_range;

-- Best value restaurants — high rating, low cost, high votes

SELECT * FROM zomatodata;

SELECT RestaurantName, City, Cuisines, Average_Cost_for_two, Rating, Votes
FROM zomatodata WHERE CountryCode = 1
  AND Rating >= 4.0
  AND Average_Cost_for_two <= 500
  AND Votes >= 200
ORDER BY Rating DESC, Votes DESC
LIMIT 20;


-- Price range vs average rating
SELECT CASE
    WHEN Average_Cost_for_two < 300 THEN 'Budget (under 300)'
    WHEN Average_Cost_for_two BETWEEN 300 AND 700 THEN 'Mid (300-700)'
    WHEN Average_Cost_for_two BETWEEN 700 AND 1500 THEN 'Premium (700-1500)'
    ELSE 'Fine Dining (1500+)'
  END AS price_category,
  COUNT(*) AS restaurant_count,
  ROUND(AVG(Rating), 2) AS avg_rating,
  ROUND(AVG(Votes), 0) AS avg_votes
FROM zomatodata WHERE CountryCode = 1 AND Rating > 0
GROUP BY price_category ORDER BY avg_rating DESC;

ALTER TABLE `zomato_db`.`zomatodata_backup` 
RENAME TO  `zomato_db`.`zomatodata` ;



